POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "bingus",
    "number": "040--1213121323"
}

###


PUT http:localhost:3001/api/
###

DELETE http://localhost:3001/api/persons/67669237e90206c3dda72fe0



